import argparse
import json
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from shared import (
    APP_DIR_PATH,
    CHANGE_TYPE_MAP,
    DEV_SERVER_URL,
    E2E_DIR_PATH,
    EVAL_OUTPUTS_DIR_PATH,
    HOME_TSX_PATH,
    ITERATION_MAP,
    MODEL_OUTPUTS_PATH,
    REPO_ROOT_PATH,
    VERSIONS_ROOT_PATH,
    extract_typescript,
)


def generate_output_directory(record: dict) -> Path:
    """
    Mirror MODEL_OUTPUTS_PATH directory structure under eval_outputs directory for easier comparison
    """
    parts = Path(record["file"]).parts

    # Drop the first part (model_outputs) and the last part (filename) to get the subdirectory
    return EVAL_OUTPUTS_DIR_PATH.joinpath(*parts[1:-1])


def get_prompt_type(record: dict) -> str:
    """Extract prompt type"""
    return record["prompt_type"]


def uncomment_file(src: Path, dst: Path) -> None:
    """
    To avoid linting errors in version specific tsx files, they are commented out with '//'.
    This function removes the leading '// ' from every line and writes to the destination path
    I.E so that the version specific file is written to actual Home.tsx file for the Playwright test run
    """

    # Read the source file
    raw = src.read_text()

    # Regex check to remove the comments
    lines = [re.sub(r"^// ?", "", line) for line in raw.splitlines()]

    # Write the uncommented content to the destination file
    dst.write_text("\n".join(lines))


def start_dev_server() -> subprocess.Popen:
    """
    Start the Vite dev server and block until it responds on DEV_SERVER_URL.
    This is necessary to ensure the app is running, ready to serve the test page
    against which the Playwright tests will run.
    """
    # Use a sub process to start the actual web app
    proc = subprocess.Popen(
        ["npm", "run", "dev"],
        cwd=APP_DIR_PATH,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    # Debug statement
    print(f"Starting dev server (pid {proc.pid})...", end=" ", flush=True)

    # Allow up to 30 seconds for the dev server to be up and responsive
    for _ in range(30):
        try:
            urllib.request.urlopen(DEV_SERVER_URL, timeout=2)
            print("ready.")
            return proc
        except (urllib.error.URLError, OSError):
            time.sleep(1)

    # If not running within 30 seconds, terminate the process and raise an error
    proc.terminate()
    raise RuntimeError(
        f"Dev server did not become ready at {DEV_SERVER_URL} within 30s"
    )


def stop_dev_server(proc: subprocess.Popen) -> None:
    """
    This function ensures server stops after each test finishes to ensure clean state
    for next test.
    """

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
    print("Dev server stopped.")


def run_playwright(
    code: str,
    iteration: str,
    change_type: str,
    prompt_type: str,
    output_directory: Path,
) -> dict:
    """
    This function takes the generated test code from the model and runs it with Playwright,
    returning the results. Also handles setup of Home.tsx based on iteration and change type.
    """

    # First create target output directory if it doesn't exist
    output_directory.mkdir(parents=True, exist_ok=True)

    # Name of temporary test spec file that Playwright will run against
    temp_spec = E2E_DIR_PATH / f"{prompt_type}.spec.ts"

    # Output paths for the generated test spec and the log file to capture Playwright output
    # Note .txt extension to avoid linting issues with generated code
    out_spec = output_directory / f"{prompt_type}.txt"
    out_log = output_directory / f"{prompt_type}.log"

    # Construct path to the version specific Home.tsx file based on iteration and change type
    changes_dir = ITERATION_MAP.get(iteration)
    versions_dir = CHANGE_TYPE_MAP.get(change_type)
    version_home = (
        VERSIONS_ROOT_PATH / versions_dir / changes_dir / "Home.tsx"
        if (changes_dir and versions_dir)
        else None
    )

    # Validation check to ensure that Home.tsx file exists for given iteration and change type
    if (
        not changes_dir
        or not versions_dir
        or not version_home
        or not version_home.exists()
    ):
        out_log.write_text("ERROR: missing version Home.tsx\n")
        return {
            "playwright_passed": False,
            "playwright_failed": -1,
            "playwright_errors": -1,
            "playwright_error_msg": "missing version Home.tsx",
        }

    # Validation check to ensure that some code was generated by the model before attempting to run
    if not code.strip():
        out_log.write_text("ERROR: empty generated code\n")
        return {
            "playwright_passed": False,
            "playwright_failed": 0,
            "playwright_errors": 1,
            "playwright_error_msg": "empty generated code",
        }

    # Backup the current Home.tsx file so it can be restored after each test
    home_backup = HOME_TSX_PATH.read_text() if HOME_TSX_PATH.exists() else None

    try:
        # Uncomment the specific version into the target Home.tsx location which Playwright will run
        uncomment_file(version_home, HOME_TSX_PATH)

        # Extract test code from the model output
        extracted = extract_typescript(code)

        # Write extracted test code to a temp spec file that Playwright will run against
        temp_spec.write_text(extracted)

        # Construct path for artefacts from Playwright (screenshots, videos, traces)
        artifacts_dir = output_directory / "artefacts" / prompt_type

        # Take timestamp (used for measuring total execution time)
        t_start = time.time()

        # Use subprocess to run Playwright tests against generated spec file,
        # capturing output and including timeout to prevent long delays on
        # broken tests. Run with workers=1 to avoid issues with concurrent
        # test runs.
        result = subprocess.run(
            [
                "npx",
                "playwright",
                "test",
                temp_spec.name,
                "--reporter=line",
                "--timeout=20000",
                "--workers=1",
                "--output",
                str(artifacts_dir),
            ],
            cwd=APP_DIR_PATH,
            capture_output=True,
            text=True,
            timeout=180,
        )

        # Persist outputs to eval_outputs/ for auditing after
        shutil.copy(temp_spec, out_spec)

        # Write Playwright output (standard output, standard error and return code to the log file)
        out_log.write_text(
            f"=== RETURN CODE: {result.returncode} ===\n\n"
            f"=== STDOUT ===\n{result.stdout}\n\n"
            f"=== STDERR ===\n{result.stderr}\n"
        )

        # Calculate total execution time after test has completed
        execution_time_s = round(time.time() - t_start, 2)

        # Determine if test has passed or failed
        ok = result.returncode == 0

        # Use regex to extract number of passed / failed tests from Playwright output
        failed_match = re.search(r"(\d+) failed", result.stdout)
        passed_match = re.search(r"(\d+) passed", result.stdout)

        # Use regex results to determine numbers of passed and failed tests if matches
        # Otherwise fallback to binary pass/fail based on return code
        failed = int(failed_match.group(1)) if failed_match else (0 if ok else 1)
        passed = int(passed_match.group(1)) if passed_match else (1 if ok else 0)

        # Capture results in structured output
        return {
            "playwright_passed": ok,
            "playwright_failed": failed,
            "playwright_passed_count": passed,
            "playwright_errors": 0,
            "playwright_error_msg": "",
            "execution_time_s": execution_time_s,
        }

    # Handle timeouts for tests
    except subprocess.TimeoutExpired:
        out_log.write_text("=== TIMEOUT ===\n")
        return {
            "playwright_passed": False,
            "playwright_failed": 0,
            "playwright_errors": 1,
            "playwright_error_msg": "timeout",
        }

    # Handle any other exceptions that occur when running the tests
    except Exception as exc:
        out_log.write_text(f"=== EXCEPTION ===\n{exc}\n")
        return {
            "playwright_passed": False,
            "playwright_failed": 0,
            "playwright_errors": 1,
            "playwright_error_msg": str(exc)[:300],
        }

    # Restore core Home.tsx file to ensure each test starts with a clean file
    finally:
        if home_backup is not None:
            HOME_TSX_PATH.write_text(home_backup)
        if temp_spec.exists():
            temp_spec.unlink()


def load_model_runs_data() -> list[dict]:
    """
    This function pulls in all AI model outputs from
    the model_outputs directory and structures in a list
    so that it is easy to loop over and run Playwright tests for each record.
    """

    # Initialise empty list
    records = []

    # Extract all json files in the model_outputs directory and sub-directories
    for json_file in MODEL_OUTPUTS_PATH.rglob("*.json"):
        # Open the file
        with open(json_file) as f:
            entries = json.load(f)

        # Loop over each entry
        for entry in entries:
            # List of path parts for given file
            path_parts = json_file.parts

            # Extract iteration and change type from file path
            iteration_index = next(
                (i for i, p in enumerate(path_parts) if p in ITERATION_MAP), None
            )
            iteration = path_parts[iteration_index] if iteration_index else "unknown"
            change_type = (
                path_parts[iteration_index - 1] if iteration_index else "unknown"
            )

            # Extract relevant fields, append to list
            records.append(
                {
                    "file": str(json_file.relative_to(REPO_ROOT_PATH)),
                    "model_id": entry.get("model_id", ""),
                    "model_short": entry.get("model_id", "").split("/")[-1],
                    "prompt_type": entry.get("prompt_type", ""),
                    "scenario": entry.get("scenario", ""),
                    "iteration": iteration,
                    "inference_time_s": entry.get("metrics", {}).get(
                        "inference_time_s"
                    ),
                    "tokens_per_sec": entry.get("metrics", {}).get("tokens_per_sec"),
                    "output_token_count": entry.get("metrics", {}).get(
                        "output_token_count"
                    ),
                    "extracted_code": entry.get("content", {}).get(
                        "extracted_code", ""
                    ),
                    "change_type": change_type,
                }
            )

    # Return full list
    return records


def main() -> None:
    # Arguments parsing to allow filtering of evaluation for targeted runs
    # As there are a lot of tests
    parser = argparse.ArgumentParser(
        description="Evaluate model-generated Playwright tests"
    )
    parser.add_argument(
        "--run-tests", action="store_true", help="Run tests with Playwright"
    )
    parser.add_argument(
        "--filter-model",
        help="Only evaluate this model (substring match on short name)",
    )
    parser.add_argument("--filter-prompt", help="Only evaluate a certain prompt type")
    parser.add_argument("--filter-scenario", help="Only evaluate a certain scenario")
    parser.add_argument(
        "--filter-iteration",
        choices=list(ITERATION_MAP.keys()),
        help="Only evaluate this iteration",
    )
    args = parser.parse_args()

    print("Loading model outputs...", end=" ", flush=True)

    # Load all model outputs
    records = load_model_runs_data()

    print(f"{len(records)} records found.")

    # Allow filtering for targeted evaluation (as > 300 tests can take time)
    if args.filter_model:
        records = [
            r for r in records if args.filter_model.lower() in r["model_short"].lower()
        ]
    if args.filter_prompt:
        records = [r for r in records if r["prompt_type"] == args.filter_prompt]
    if args.filter_scenario:
        records = [r for r in records if r["scenario"] == args.filter_scenario]
    if args.filter_iteration:
        records = [r for r in records if r["iteration"] == args.filter_iteration]

    # Ensure breaks if no records match filter critera
    if not records:
        print("No records match the given filters.")
        sys.exit(1)

    # If --run-tests provided as flag, loop over each and run tests
    if args.run_tests:
        # Keep track of results in JSON file for easier analysis after test run
        jsonl_path = EVAL_OUTPUTS_DIR_PATH / "results.jsonl"

        # If eval_outputs directory does not exist, create it
        EVAL_OUTPUTS_DIR_PATH.mkdir(exist_ok=True)

        # Start the actual web app version that Playwright tests will run against
        dev_server = start_dev_server()
        try:
            print(f"\nRunning Playwright tests ({len(records)} total)...")

            # Open the results file to write to it as we go
            with open(jsonl_path, "w") as jsonl_file:
                # Loop over the records
                for i, r in enumerate(records, 1):
                    # Extract this info for logging and output dir creation purposes
                    label = f"{r['model_short']} / {r['prompt_type']} / {r['iteration']} / {r['scenario']} / {r.get('change_type', '')}"
                    print(f"  [{i}/{len(records)}] {label}", end=" ", flush=True)

                    # Determine prompt type and output dir for this test
                    prompt_type = get_prompt_type(r)
                    output_directory = generate_output_directory(r)

                    # Run Playwright test for the current given record and record results
                    pw = run_playwright(
                        r["extracted_code"],
                        r["iteration"],
                        r["change_type"],
                        prompt_type,
                        output_directory,
                    )

                    # Update the existing record with Playwright output
                    r.update(pw)

                    # Construct status message based on result
                    status = (
                        "PASS"
                        if pw["playwright_passed"]
                        else f"FAIL ({pw['playwright_failed']} failed)"
                    )
                    # Print for debuggin
                    print(f"{status}  ({pw.get('execution_time_s', '?')}s)")

                    # Write line to JSONl results file with the original record and the
                    # Playwright results for a full analysis after
                    result_row = {
                        "model": r["model_short"],
                        "prompt_type": r["prompt_type"],
                        "scenario": r["scenario"],
                        "iteration": r["iteration"],
                        "change_type": r.get("change_type", ""),
                        "passed": pw["playwright_passed"],
                        "failed_count": pw["playwright_failed"],
                        "passed_count": pw.get("playwright_passed_count", 0),
                        "test_count": r.get("test_count", 0),
                        "execution_time_s": pw.get("execution_time_s"),
                        "inference_time_s": r.get("inference_time_s"),
                        "tokens_per_sec": r.get("tokens_per_sec"),
                        "output_token_count": r.get("output_token_count"),
                    }

                    # Write the result row and new line
                    jsonl_file.write(json.dumps(result_row) + "\n")

                    # Flush to ensure incremental writes
                    jsonl_file.flush()
                    time.sleep(1)
        finally:
            # Once all tests are done, stop the actual web app
            stop_dev_server(dev_server)

        print(f"\nResults written to {jsonl_path}")


if __name__ == "__main__":
    main()
